### ISSUE TITLE
Switched templating engine from Metalsmith to Hugo 

### ISSUE THREAD

**Issue by pcraig3** [RobinThrift/RobinThrift.com#8]
Hello mate,

Not an issue as such, but just a question I had.
I've just been reading along some of your blog posts about Metalsmith (which I think looks interesting), but it seems that in the past year you've switched over to Hugo. Any reason in particular?  ie, Was it because Metalsmith was hard to use or just because you were keen to try out something new?

**Comment by RobinThrift** [comment]
Just because I wanted to try something new, and very low maintenance. Metalsmith is a great tool, but it was a lot of work to keep it up to date. Also Hugo's more "convention over configuration" approach suited be better now that I have less time.

Hope that answers your question, if not, feel free to ask more questions here :)

**Comment by pcraig3** [comment]
Yup, that answers it nicely. Was just wondering if you ran into any show-stopping problems, but it doesn't seem like it.  Thanks for the quick response!
